// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Pooled connection for runtime queries (via PgBouncer)
    url: process.env["DATABASE_URL"],
<<<<<<< HEAD
=======
    // Direct connection required for Prisma Migrate
    directUrl: process.env["DIRECT_URL"],
>>>>>>> de6ae46f9d4b0617971cff8a32dce976fd74eca5
  },
});
