import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#4edea3",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#79000e",
        "on-surface-variant": "#3c4a42",
        "outline-variant": "#bbcabf",
        "inverse-on-surface": "#edf0ff",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#00422b",
        "surface-variant": "#dce2f7",
        "on-background": "#141b2b",
        "surface-container-high": "#e1e8fd",
        "surface": "#f9f9ff",
        "error-container": "#ffdad6",
        "secondary": "#376850",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002113",
        "secondary-fixed-dim": "#9ed2b5",
        "tertiary": "#b91a24",
        "on-primary": "#ffffff",
        "secondary-container": "#b7ebce",
        "surface-container-low": "#f1f3ff",
        "surface-container-highest": "#dce2f7",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#005236",
        "outline": "#6c7a71",
        "primary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-tertiary-fixed": "#410004",
        "on-surface": "#141b2b",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdad7",
        "surface-bright": "#f9f9ff",
        "tertiary-container": "#ff7a73",
        "background": "#f9f9ff",
        "primary": "#006c49",
        "inverse-surface": "#293040",
        "primary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#10b981",
        "surface-tint": "#006c49",
        "on-secondary-fixed-variant": "#1e4f3a",
        "on-secondary-container": "#3c6c54",
        "surface-container": "#e9edff",
        "secondary-fixed": "#baeed1",
        "on-tertiary-fixed-variant": "#930013",
        "surface-dim": "#d3daef"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
};
export default config;
